### ISSUE TITLE
The testnet CheckTransactionSanity failed when verifiy block. Blocks cannot download after blcok height 501.

### ISSUE THREAD

**Issue by anthonymo** [cyber-republic/develap#1]
After running /develap blockchain run -e testnet -n mainchain,did,token,eth. The testnet running but failed to verify block to download the new blocks.

CONTAINER ID        IMAGE                                               COMMAND                  CREATED             STATUS                    PORTS                                                                                 NAMES
13dcc93363f0        cyberrepublic/elastos-sidechain-eth-node:latest     "/bin/sh -c './geth …"   4 minutes ago       Up 4 minutes              20635/tcp, 20638/tcp, 20638/udp, 0.0.0.0:21634->20634/tcp, 0.0.0.0:21636->20636/tcp   develap-testnet-eth-node
af9dee7151b6        cyberrepublic/elastos-sidechain-token-node:v0.1.2   "/bin/sh -c ./token"     4 minutes ago       Up 4 minutes              0.0.0.0:21614->21614/tcp, 20614-20618/tcp, 0.0.0.0:21616->21616/tcp                   develap-testnet-token-node
4d13ea6f12ed        cyberrepublic/elastos-sidechain-did-node:v0.1.2     "/bin/sh -c ./did"       4 minutes ago       Up 4 minutes              0.0.0.0:21604->21604/tcp, 20604-20608/tcp, 0.0.0.0:21606->21606/tcp                   develap-testnet-did-node
0eda59ea74c1        cyberrepublic/elastos-mainchain-node:v0.3.7         "/bin/sh -c './ela -…"   4 minutes ago       Up 4 minutes              0.0.0.0:21334->21334/tcp, 20333-20339/tcp, 0.0.0.0:21336->21336/tcp                   develap-testnet-mainchain-node

2020/08/23 23:19:35.012796 [1;35m[INF][m GID 1, Node version: 
2020/08/23 23:19:35.012975 [1;35m[INF][m GID 1, go version go1.12.9 linux/amd64
2020/08/23 23:19:35.111834 [1;35m[INF][m GID 1, current block height -> 500
2020/08/23 23:19:35.112461 [1;33m[WRN][m GID 43, recover form check points fail:  can't find dpos store object
2020/08/23 23:19:35.112637 [1;35m[INF][m GID 43, [RecoverFromCheckPoints] recover start height:  200000
2020/08/23 23:19:35.113449 [1;35m[INF][m GID 1, Start the P2P networks
2020/08/23 23:19:35.113558 [1;35m[INF][m GID 1, Start services
2020/08/23 23:19:35.745568 [1;35m[INF][m GID 22, New valid peer 18.213.224.198:21338 (outbound)
2020/08/23 23:19:35.746808 [1;35m[INF][m GID 22, Syncing to block height 608942 from peer 18.213.224.198:21338
2020/08/23 23:19:35.747321 [1;35m[INF][m GID 22, New valid peer 3.212.18.196:21338 (outbound)
2020/08/23 23:19:35.747428 [1;35m[INF][m GID 22, New valid peer 18.206.41.124:21338 (outbound)
2020/08/23 23:19:35.747521 [1;35m[INF][m GID 22, New valid peer 18.207.43.194:21338 (outbound)
2020/08/23 23:19:35.747587 [1;35m[INF][m GID 22, New valid peer 34.196.161.95:21338 (outbound)
2020/08/23 23:19:35.747628 [1;35m[INF][m GID 22, New valid peer 18.205.31.224:21338 (outbound)
2020/08/23 23:19:35.747693 [1;35m[INF][m GID 22, New valid peer 3.210.98.16:21338 (outbound)
2020/08/23 23:19:38.157241 [1;33m[WRN][m GID 22, [CheckTransactionOutput], First output address should be foundation address.
2020/08/23 23:19:38.157510 [1;35m[INF][m GID 22, Rejected block 80e307d811057abad33c16e5688494147ff5140963ab27a3d358260916a44fd5 from 18.213.224.198:21338 (outbound): CheckTransactionSanity failed when verifiy block
2020/08/23 23:20:05.703487 [1;35m[INF][m GID 22, New valid peer 3.209.59.41:21338 (outbound)
2020/08/23 23:20:12.148309 [1;33m[WRN][m GID 22, [CheckTransactionOutput], First output address should be foundation address.
2020/08/23 23:20:12.148930 [1;35m[INF][m GID 22, [AppendBlock] check block sanity failed,  CheckTransactionSanity failed when verifiy block
2020/08/23 23:20:12.149309 [1;35m[INF][m GID 22, Rejected block 4ad72333eedc3556d24f48de4e9fbad3e59ee6d367a74aadd1975f6602514e31 from 18.213.224.198:21338 (outbound): CheckTransactionSanity failed when verifiy block
2020/08/23 23:20:12.151018 [1;33m[WRN][m GID 22, [CheckTransactionOutput], First output address should be foundation address.
2020/08/23 23:20:12.151829 [1;35m[INF][m GID 22, Rejected block 4ad72333eedc3556d24f48de4e9fbad3e59ee6d367a74aadd1975f6602514e31 from 18.213.224.198:21338 (outbound): CheckTransactionSanity failed when verifiy block
2020/08/23 23:20:15.906045 [1;33m[WRN][m GID 22, [CheckSideChainPowConsensus], Arbitrator is not matched. [Validation], Verify failed.
2020/08/23 23:20:15.906322 [1;33m[WRN][m GID 22, [TxPool CheckTransactionContext] failed 2b497e4ee14dce5b185529e47e640cd2df6798321cb779e735f6e5bb75bec8ab
2020/08/23 23:20:15.907652 [1;33m[WRN][m GID 22, [CheckSideChainPowConsensus], Arbitrator is not matched. [Validation], Verify failed.
2020/08/23 23:20:15.907856 [1;33m[WRN][m GID 22, [TxPool CheckTransactionContext] failed da63c3cfe7595954dc90ab7ad9b99e7d4a2b5a54911a24455b61226b169ab17d
2020/08/23 23:20:15.909024 [1;33m[WRN][m GID 22, [CheckSideChainPowConsensus], Arbitrator is not matched. [Validation], Verify failed.
2020/08/23 23:20:15.909205 [1;33m[WRN][m GID 22, [TxPool CheckTransactionContext] failed 399e8f3affe6e351f0d1395282f6ab3410ba8e2e4a2fe446e3a2b7d433772b3d
2020-08-23 23:20:35.114 [INF] STAT: -> 1000 [608942 34.196.161.95:21338 (outbound), 608942 18.205.31.224:21338 (outbound), 608942 3.210.98.16:21338 (outbound), 608942 3.209.59.41:21338 (outbound), 608942 18.213.224.198:21338 (outbound), 608942 3.212.18.196:21338 (outbound), 608942 18.206.41.124:21338 (outbound), 608942 18.207.43.194:21338 (outbound)]
2020/08/23 23:20:36.593432 [1;33m[WRN][m GID 22, [CheckTransactionOutput], First output address should be foundation address.
2020/08/23 23:20:36.593500 [1;35m[INF][m GID 22, [AppendBlock] check block sanity failed,  CheckTransactionSanity failed when verifiy block
2020/08/23 23:20:36.593554 [1;35m[INF][m GID 22, Rejected block b7fdf5d8399c97e90e056b360050ce26515534225a0e6f97281188256c8428a3 from 18.213.224.198:21338 (outbound): CheckTransactionSanity failed when verifiy block
2020/08/23 23:20:36.593758 [1;33m[WRN][m GID 22, [CheckTransactionOutput], First output address should be foundation address.
2020/08/23 23:20:36.593829 [1;35m[INF][m GID 22, Rejected block b7fdf5d8399c97e90e056b360050ce26515534225a0e6f97281188256c8428a3 from 18.213.224.198:21338 (outbound): CheckTransactionSanity failed when verifiy block
2020/08/23 23:20:41.053290 [1;33m[WRN][m GID 22, [CheckSideChainPowConsensus], Arbitrator is not matched. [Validation], Verify failed.
2020/08/23 23:20:41.053688 [1;33m[WRN][m GID 22, [TxPool CheckTransactionContext] failed 77413709ee035f3e804f3cfe34bc2f566978d338f823a01c13154b2c78d74a0d
2020/08/23 23:20:41.056839 [1;33m[WRN][m GID 22, [CheckSideChainPowConsensus], Arbitrator is not matched. [Validation], Verify failed.
2020/08/23 23:20:41.057145 [1;33m[WRN][m GID 22, [TxPool CheckTransactionContext] failed ffa95c541045e675281a9e27ba45022d97282066676e480d15e037a9b2a706b7
2020/08/23 23:20:41.059800 [1;33m[WRN][m GID 22, [CheckSideChainPowConsensus], Arbitrator is not matched. [Validation], Verify failed.
2020/08/23 23:20:41.060063 [1;33m[WRN][m GID 22, [TxPool CheckTransactionContext] failed 576a616949b5f4457625a13be1ca45725f81db8e33dd6e0e544347d3273390d7
2020-08-23 23:21:35.115 [INF] STAT: -> 1000 [608944 34.196.161.95:21338 (outbound), 608944 18.205.31.224:21338 (outbound), 608944 3.210.98.16:21338 (outbound), 608944 3.209.59.41:21338 (outbound), 608944 18.213.224.198:21338 (outbound), 608944 3.212.18.196:21338 (outbound), 608944 18.206.41.124:21338 (outbound), 608944 18.207.43.194:21338 (outbound)]
2020-08-23 23:22:35.114 [INF] STAT: -> 1000 [608944 3.212.18.196:21338 (outbound), 608944 18.206.41.124:21338 (outbound), 608944 18.207.43.194:21338 (outbound), 608944 34.196.161.95:21338 (outbound), 608944 18.205.31.224:21338 (outbound), 608944 3.210.98.16:21338 (outbound), 608944 3.209.59.41:21338 (outbound), 608944 18.213.224.198:21338 (outbound)]
2020-08-23 23:23:35.114 [INF] STAT: -> 1000 [608944 18.206.41.124:21338 (outbound), 608944 18.207.43.194:21338 (outbound), 608944 34.196.161.95:21338 (outbound), 608944 18.205.31.224:21338 (outbound), 608944 3.210.98.16:21338 (outbound), 608944 3.209.59.41:21338 (outbound), 608944 18.213.224.198:21338 (outbound), 608944 3.212.18.196:21338 (outbound)]
2020-08-23 23:24:35.114 [INF] STAT: -> 1000 [608944 34.196.161.95:21338 (outbound), 608944 18.205.31.224:21338 (outbound), 608944 3.210.98.16:21338 (outbound), 608944 3.209.59.41:21338 (outbound), 608944 18.213.224.198:21338 (outbound), 608944 3.212.18.196:21338 (outbound), 608944 18.206.41.124:21338 (outbound), 608944 18.207.43.194:21338 (outbound)]
2020-08-23 23:25:35.114 [INF] STAT: -> 1000 [608944 3.209.59.41:21338 (outbound), 608944 18.213.224.198:21338 (outbound), 608944 3.212.18.196:21338 (outbound), 608944 18.206.41.124:21338 (outbound), 608944 18.207.43.194:21338 (outbound), 608944 34.196.161.95:21338 (outbound), 608944 18.205.31.224:21338 (outbound), 608944 3.210.98.16:21338 (outbound)]
2020-08-23 23:26:35.114 [INF] STAT: -> 1000 [608944 18.206.41.124:21338 (outbound), 608944 18.207.43.194:21338 (outbound), 608944 34.196.161.95:21338 (outbound), 608944 18.205.31.224:21338 (outbound), 608944 3.210.98.16:21338 (outbound), 608944 3.209.59.41:21338 (outbound), 608944 18.213.224.198:21338 (outbound), 608944 3.212.18.196:21338 (outbound)]
2020/08/23 23:27:11.303786 [1;33m[WRN][m GID 22, [CheckTransactionOutput], First output address should be foundation address.
2020/08/23 23:27:11.303877 [1;35m[INF][m GID 22, [AppendBlock] check block sanity failed,  CheckTransactionSanity failed when verifiy block
2020/08/23 23:27:11.303916 [1;35m[INF][m GID 22, Rejected block 3781420037e75f4fe0ec0a8821e7ba47f0124e074e60fd4e90f01b1c6879c6e1 from 18.213.224.198:21338 (outbound): CheckTransactionSanity failed when verifiy block
2020/08/23 23:27:11.304203 [1;33m[WRN][m GID 22, [CheckTransactionOutput], First output address should be foundation address.
2020/08/23 23:27:11.304234 [1;35m[INF][m GID 22, Rejected block 3781420037e75f4fe0ec0a8821e7ba47f0124e074e60fd4e90f01b1c6879c6e1 from 18.213.224.198:21338 (outbound): CheckTransactionSanity failed when verifiy block
2020/08/23 23:27:15.912082 [1;33m[WRN][m GID 22, [CheckSideChainPowConsensus], Arbitrator is not matched. [Validation], Verify failed.
2020/08/23 23:27:15.912150 [1;33m[WRN][m GID 22, [TxPool CheckTransactionContext] failed f21e39a8850a73c8fbc12a5e7eff8d48236b46b9d957f22c7cc6c4df0133f476
2020/08/23 23:27:15.912565 [1;33m[WRN][m GID 22, [CheckSideChainPowConsensus], Arbitrator is not matched. [Validation], Verify failed.
2020/08/23 23:27:15.912612 [1;33m[WRN][m GID 22, [TxPool CheckTransactionContext] failed 4cca924621df6be02b7d1151402c88c66c814053648243bf1bd3d59fc085f677
2020/08/23 23:27:15.912984 [1;33m[WRN][m GID 22, [CheckSideChainPowConsensus], Arbitrator is not matched. [Validation], Verify failed.
2020/08/23 23:27:15.913024 [1;33m[WRN][m GID 22, [TxPool CheckTransactionContext] failed 06c300a5ac4f2d609990a3417e2d88e5066908f55ca032af8dc0c5f16bd26e69

**Comment by kpachhai** [comment]
New update was pushed today. Also, the above error may more be related to the blockchain itself, not the develap tool
